src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Veuillez renseigner un email")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=30)
	 *
	 * @Assert\NotBlank(message="Veuillez renseigner un prénom")
	 * @Assert\Length(
	 *	min=2,
	 *	max=30,
	 *  minMessage="Veuillez renseigner un prénom de 2 caractères mini",
	 *  maxMessage="Veuillez renseigner un prénom de 30 carctères maxi"
	 * )
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50)
	 *
	 * @Assert\NotBlank(message="Veuillez renseigner un nom")
	 * @Assert\Length(
	 *	min=2,
	 *	max=50,
	 *  minMessage="Veuillez renseigner un nom de 2 caractères mini",
	 *  maxMessage="Veuillez renseigner un nom de 50 carctères maxi"
	 * )
     */
    private $nom;


    /**
     * @ORM\Column(type="string", length=50)
	 * @Assert\NotBlank(message="Veuillez renseigner une ville")
	 * @Assert\Length(
	 *	min=2,
	 *	max=50,
	 *  minMessage="Veuillez renseigner une ville de 2 caractères mini",
	 *  maxMessage="Veuillez renseigner une ville de 50 carctères maxi"
	 * )
     */
    private $ville;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Regex("/^[0-9]{5}/")
	 * @Assert\Type(type="integer", message="Veuillez renseigner un code postal composé de chiffres.")
     */
    private $codePostal;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner une adresse")
     */
    private $adresse;


    /**
     * @ORM\Column(type="string", length=25)
	 * @Assert\Regex(
	 *	pattern="/^0[1-9]([-. ]?[0-9]{2}){4}$/",
	 *	message="Mauvais numero de téléphone"
	 *)
     */
    private $telephone;




    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;


    /**
     * @ORM\Column(type="date")
     */
    private $register_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->codePostal;
    }

    public function setCodePostal(int $codePostal): self
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }






    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }



    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    public function getRoles()
    {
        return [$this->roles];
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getRegisterAt(): ?\DateTimeInterface
    {
        return $this->register_at;
    }

    public function setRegisterAt(\DateTimeInterface $register_at): self
    {
        $this->register_at = new \DateTime('now');

        return $this;
    }

    public function getStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserFormType;
use App\Entity\PasswordUpdate;
use App\Form\PasswordUpdateType;
use Symfony\Component\Form\FormError;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{

    /**
     * @Route("/inscription", name="inscription")
     */
    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserFormType::class, $user, array(
            'inscription' => true
        ));
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $time = new \DateTime('now');
            $user->setRegisterAt($time);
            $user->setRoles("ROLE_USER");
            $user->setStatut(0);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('connexion');
        }

        return $this->render('security/inscription.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    
    /**
     * @Route("/connexion", name="connexion")
     */
    public function connexion(AuthenticationUtils $util)
    {
        return $this->render('security/connexion.html.twig',[
            "lastUserName" => $util->getLastUsername(),
            "error" =>$util->getLastAuthenticationError()
        ]);
    }

    /**
	 * @Route("/roles", name="roles")
	 *
	 */
	public function roles() 
	{
        if ($this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('dashboard');
        }
        else{
            return $this->redirectToRoute('accueil'); 
        }

        
	}


    /**
	 * @Route("/check", name="check")
	 *
	 */
	public function connexionCheck()
    { 

    }
    
    /**
     * @Route("/deconnexion", name="deconnexion")
     */
    public function deconnexion()
    {

    }


    /**
     * @Route("/profil/{id}", name="profil")
     */
    public function profil(User $user)
    {   
        
        return $this->render('security/profil.html.twig',[
            'user' => $user
        ]);
    }



    /**
     * @Route("/profil_modification/{id}", name="profil_modification", methods={"GET","POST"})
     */

    public function modificationProfil(User $user, Request $request)
    {   
        $form = $this->createForm(UserFormType::class, $user, array('profil' => true));
        $form -> handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid())
        {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('profil', $user->getPrenom().' votre profil a bien été modifié');
        	return $this->redirectToRoute('profil', array('id' => $user->getId()));
        }

        return $this -> render('security/profil_modification.html.twig', [
            'userForm' => $form->createView(),
            'user' => $user
        ]);
    }
        

    /**
     * @Route("/suppresionProfil/{id}", name="profil_suppression", methods={"DELETE"})
     */
    public function suppressionProfil(Request $request, User $user): Response
    {
        
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token')))
        {
            $session = new Session();
            $session->invalidate();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();

            $this->addFlash('sup', 'Votre compte a bien été supprimée');
        }

        return $this->redirectToRoute('accueil');
    }





    /**
     * @Route("/password_modification/{id}", name="password_modification")
     */

    public function modificationPassword(User $user, Request $request, UserPasswordEncoderInterface $encoder, EntityManagerInterface $manager) 
    {
        $passwordUpdate = new PasswordUpdate();
        $form = $this->createForm(PasswordUpdateType::class, $passwordUpdate);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            if(!password_verify($passwordUpdate->getOldPassword(), $user->getPassword()))
            {
                $form->get('oldPassword')->addError(new FormError("Le mot de passe que vous avez tapé n'est pas votre mot de passe actuel !"));
            } 
            else
            {
                $newPassword = $passwordUpdate->getNewPassword();
                $hash = $encoder->encodePassword($user, $newPassword);
                $user->setPassword($hash);
                $manager->persist($user);
                $manager->flush();

                $this->addFlash('success', "Votre mot de passe a bien été modifié !" );

                return $this->redirectToRoute('accueil');
            }
        }


        return $this->render('security/password_modification.html.twig', [
            'form' => $form->createView(),
            'user' => $user
        ]);
    }
}

templates/security/connexion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Connexion{% endblock %}
{% block monTitre %}Connexion{% endblock %}

{% block body %}
{% if error %}
    <div class="alert alert-danger d-inline-block">
        {{ error.messageKey | trans(error.messagedata, 'security') }}
    </div>
{% endif %}
<hr style='background:white'>
<div class="row justify-content-center">
    <div class="col-6 text-center ">

        <form action="{{ path('check') }}" method="post">
            <div class="form-group">
                <label>Email : </label>
                <input type="text" required name="_username" class="form-control" >
            </div>
            <div class="form-group">
                <label>Mot de passe : </label>
                <input type="password" required name="_password" class="form-control">
            </div>
            <input type="submit" class="btn btn-info" value="Connexion">
        </form>

        <a class="nav-link" href="{{ path('inscription') }}">Inscrivez-vous</a>

    </div>
</div>
    
{% endblock %}

templates/security/inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}
{% block monTitre %}Inscription{% endblock %}

{% block body %}
<hr style='background:white'>
<div class="row justify-content-center">
    <div class="col-6 text-center ">


{{form_start(form)}}
    {{ form_row(form.email) }}
        <div class="row">
            <div class="col-6">
            {{ form_row(form.plainPassword.first) }}
            </div>
            <div class="col-6">
            {{ form_row(form.plainPassword.second) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">
            {{ form_row(form.prenom) }}
            </div>
            <div class="col-6">
            {{ form_row(form.nom) }}
            </div>
        </div>
    
    {{ form_row(form.telephone) }}    
    {{ form_row(form.adresse) }}

        <div class="row">
            <div class="col-3">
            {{ form_row(form.codePostal) }}
            </div>
            <div class="col-9">
            {{ form_row(form.ville) }}
            </div>
        </div>

    {{ form_row(form.agreeTerms) }}
    <input type="submit" class="btn btn-info pr-4 pl-4" value="S'inscrire">
{{form_end(form)}}



    </div>
</div>
{% endblock %}

templates/security/password_modification.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modification de ton profil {% endblock %}
{% block monTitre %}Modification de ton profil {% endblock %}
{% block body %}

 <div class="container clearfix row justify-content-center">

    <div class="col-6">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <a href="{{ path('profil', { id : user.id }) }}" class=" btn btn-primary">Précédent</a>
        <button type="submit" class="btn btn-success float-right">Modifier le mot de passe</button>
        {{ form_end(form) }}
    </div>

</div>


{% endblock %}

templates/security/profil.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% for message in app.flashes('profil') %}
        <div class="alert alert-success d-inline-block">
            {{ message }}
        </div>
    {% endfor %}
    {% for message in app.flashes('notice') %}
        <div class="alert alert-success d-inline-block">
            {{ message }}
        </div>
    {% endfor %}

    <div class='banniere_form'>
        <h2 class="card-header info-color white-text text-center py-4">Informations du profil</h2>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card h-100">
                    <div class="card-body text-center">
                        <h4 class="card-title text-info"><strong> {{ user.prenom }} {{ user.nom }}</strong></h4>
                        <p class="card-text"><strong>{{ user.adresse }}</strong></p>
                        <p class="card-text"><strong>{{ user.codePostal }} {{ user.ville }}</strong></p>
                        <p class="card-text"><strong>{{ user.email }}</strong></p>
                        <p class="card-text"><strong>{{ user.telephone }}</strong></p>
                        <hr>
                        <h4 class="card-title text-info"><strong>Inscription</strong></h4>
                        <p class="card-text"><strong>{{ user.registerAt|date("d M Y") }}</strong></p>

                        <div class="row justify-content-start ">
                            <a class=" btn btn-info" href="{{ path('profil_modification', {id : user.id}) }}">Modifier votre profil</a>
                            <a class=" btn btn-info" href="{{ path('password_modification', {id : user.id}) }}">Modifier votre mot de passe</a>
                            <form method="post" class=" col-6" action="{{ path('profil_suppression', {'id': user.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer votre compte ?');">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
                                <button class="btn btn-danger col-12">Supprimer votre compte</button>
                            </form>
                        </div>
                            
                        
                    </div>

         
                   


                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/security/profil_modification.html.twig
{% extends 'base.html.twig' %}
{% block title %}Modification de ton profil {% endblock %}
{% block monTitre %}Modification de ton profil {% endblock %}
{% block body %}

    {{ form_start(userForm) }}

    <div class="row justify-content-center">
        <div class="col-8">

        <div class="row">
            <div class="col-6">
            {{ form_row(userForm.prenom) }}
            </div>
            <div class="col-6">
            {{ form_row(userForm.nom) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">
            {{ form_row(userForm.email) }}
            </div>
            <div class="col-6">
            {{ form_row(userForm.telephone) }}
            </div>
        </div>

        <div class="row">
            <div class="col-4">
            {{ form_row(userForm.adresse) }}
            </div>
            <div class="col-2">
            {{ form_row(userForm.codePostal) }}
            </div>
            <div class="col-6">
            {{ form_row(userForm.ville) }}
            </div>
        </div>


        <a href="{{ path('profil', { id : user.id }) }}" class=" btn btn-primary">Précédent</a>
        <button type="submit" class="btn btn-success float-right">Modifier le profil</button>
            
        </div>
    </div>

    

    {{ form_end(userForm) }}



{% endblock %}